using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MoveLeft : MonoBehaviour
{

    private float _speed = 30;
    private PlayerController _playerControllerScript;
    private float _leftBound = -15;
    // Start is called before the first frame update
    void Start()
    {
        _playerControllerScript = GameObject.Find("Player").GetComponent<PlayerController>();
    }

    // Update is called once per frame
    void Update()
    {
        if (_playerControllerScript.gameOver == false)
        {
            transform.Translate(Vector3.left * (Time.deltaTime * _speed));
        }

        if (transform.position.x < _leftBound&& gameObject.CompareTag("obstacle"))
        {
            Destroy(gameObject);
        }
    }
}
